config/routes.rb
Rails.application.routes.draw do
  resources :notes do  	
  	resources :comments
  end
  root 'notes#index'
  post 'notes/search', to: "notes#search", as: "search_notes"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	has_many :comments


	def self.search(search = '')
		p "----"
		p search
		if search
			where(["title LIKE ?", "%#{search}%"])
			#where("title LIKE ?", params[:search])
		else
			@user.notes.all
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :set_note, only: [:index, :create, :show, :edit, :destroy]
 before_action :set_comment, only: [:index, :show, :edit, :update, :destroy]

  def index
    @comment = @note.comments.find(params[:id])
  end

 def create
   @comment = @note.comments.new(comments_params)
   @comment.save
   redirect_to root_url
 end

def edit
end

def update
    respond_to do |format|
      if @comment.update(comments_params)
        format.html { redirect_to root_url, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

 def destroy
   @comment = @note.comments.find(params[:id]).destroy
   redirect_to root_url
 end

 private

 def set_note
   	@note = Note.find(params[:note_id])
 end

 def set_comment
   @comment = Comment.find(params[:id])
 end

 def comments_params
   params.require(:comment).permit(:point)
 end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :show, :edit, :update, :search, :destroy]

  # GET /notes
  # GET /notes.json
  def index     
    #@user = current_user 
    #@notes = @user.notes.search{params[:search]}
    @notes = @user.notes.all
    #@notes = @user.notes.where("title LIKE ?", params[:search])
  end

  def search 
    @notes = @user.notes.where("title LIKE ?", "%#{params[:search]}%")
  end 
  # GET /notes/1
  # GET /notes/1.json
  def show
    
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @user = current_user
    @note = Note.new(note_params)
    @note = @user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    p"____________________________"
    p @note

    def set_note
      @note = Note.find(params[:id])
    end

    def set_user
      @user = current_user
    end
     #Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.point %>
	<%= link_to "Delete", note_comment_path(comment.note, comment), method: :delete %>
	<%= link_to "Edit", edit_note_comment_path(comment.note, comment) %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: comment, url: [note, comment],  local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :point %>
    <%= form.text_area :point %></br>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Point</h1>

<%= render 'form', comment: @comment, note: @note %>

<%= link_to 'Show', note_comment_path %> |
<%= link_to 'Back', note_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<p>
  <strong>Point:</strong>
  <%= @comment.point %>
</p>

<%= link_to 'Edit', edit_note_comment_path(@comment) %> |
<%= link_to 'Back', note_comments_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Notes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul> 
    <li class="nav-item dropdown" style="list-style-type: none">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          
          <div class="dropdown-divider"></div>
          <%= link_to 'logout', destroy_user_session_path, method: :delete %>
          <a class="dropdown-item" href="destroy_user_session_path" method: :delete>LogOut</a>

        </div>
      </li>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_listnote.html.erb
<div>
<% notes.each do |note| %>
	<%#= note.title %>
	<%= link_to note.title, note_comments_path %>
	<%#= link_to note.title, root_path(note.id) %>
	<br>
	<% yield :comment %>

<% end %>
</div> 

app/views/notes/commentdetails.html.erb
<%# @notes.each do |note| %>

 <!--    <div style="border: 1px solid black; background-color: #add8e6;">
      
       <h3><%= note.title %></h3>
       <h2><%= note.description %></h2>
       <%= time_ago_in_words(note.created_at) %> ago by <%= note.user.email %>
       <br>

        <%#= link_to 'Edit', edit_note_path(note) %>

        <%#= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %> -->
      <%= content_for :comment %>
       <% if note.comments.any? %>

         <h4> Comments </h4>

         <%= render note.comments %>
         
       <% end %> 

       <p> Add Your Points : As comments here -- </p>
       <%= form_for([note, note.comments.build]) do |f| %>
         <%= f.text_area :point %>
         <%= submit_tag "Add" %>
       <% end %> 
       <% end %> 
     <!-- </div>
   </div>

     </div>
</div>
     <br>
     <br>
<%# end %>    -->

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Notes</h1>
<%= link_to 'Create Note', new_note_path %>
<%= form_tag search_notes_path, :method => 'post' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search"%>
<% end %>
<%= render 'listnote', notes: @notes %>
<%#= render 'commentdetails', notes: @notes %>
<% yield :comment %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>
<%= link_to 'logout', destroy_user_session_path, method: :delete %>

app/views/notes/search.html.erb
<%= render 'listnote', notes: @notes %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>